# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1344, 761)
        self.open = QAction(MainWindow)
        self.open.setObjectName(u"open")
        self.save = QAction(MainWindow)
        self.save.setObjectName(u"save")
        self.saveR = QAction(MainWindow)
        self.saveR.setObjectName(u"saveR")
        self.close = QAction(MainWindow)
        self.close.setObjectName(u"close")
        self.add = QAction(MainWindow)
        self.add.setObjectName(u"add")
        self.reverse = QAction(MainWindow)
        self.reverse.setObjectName(u"reverse")
        self.rotate = QAction(MainWindow)
        self.rotate.setObjectName(u"rotate")
        self.histogram = QAction(MainWindow)
        self.histogram.setObjectName(u"histogram")
        self.FFT = QAction(MainWindow)
        self.FFT.setObjectName(u"FFT")
        self.a1D_FFT_center = QAction(MainWindow)
        self.a1D_FFT_center.setObjectName(u"a1D_FFT_center")
        self.high = QAction(MainWindow)
        self.high.setObjectName(u"high")
        self.enlarge = QAction(MainWindow)
        self.enlarge.setObjectName(u"enlarge")
        self.shrink = QAction(MainWindow)
        self.shrink.setObjectName(u"shrink")
        self.scale = QAction(MainWindow)
        self.scale.setObjectName(u"scale")
        self.fouriour = QAction(MainWindow)
        self.fouriour.setObjectName(u"fouriour")
        self.reconstruct = QAction(MainWindow)
        self.reconstruct.setObjectName(u"reconstruct")
        self.Roberts = QAction(MainWindow)
        self.Roberts.setObjectName(u"Roberts")
        self.Sobel = QAction(MainWindow)
        self.Sobel.setObjectName(u"Sobel")
        self.Prewitt = QAction(MainWindow)
        self.Prewitt.setObjectName(u"Prewitt")
        self.Laplacian = QAction(MainWindow)
        self.Laplacian.setObjectName(u"Laplacian")
        self.resize = QAction(MainWindow)
        self.resize.setObjectName(u"resize")
        self.resizeAll = QAction(MainWindow)
        self.resizeAll.setObjectName(u"resizeAll")
        self.blend = QAction(MainWindow)
        self.blend.setObjectName(u"blend")
        self.move = QAction(MainWindow)
        self.move.setObjectName(u"move")
        self.closeR = QAction(MainWindow)
        self.closeR.setObjectName(u"closeR")
        self.r1D_FFT = QAction(MainWindow)
        self.r1D_FFT.setObjectName(u"r1D_FFT")
        self.r1D_FFT_center = QAction(MainWindow)
        self.r1D_FFT_center.setObjectName(u"r1D_FFT_center")
        self.gray = QAction(MainWindow)
        self.gray.setObjectName(u"gray")
        self.grey = QAction(MainWindow)
        self.grey.setObjectName(u"grey")
        self.low = QAction(MainWindow)
        self.low.setObjectName(u"low")
        self.Scharr = QAction(MainWindow)
        self.Scharr.setObjectName(u"Scharr")
        self.Log = QAction(MainWindow)
        self.Log.setObjectName(u"Log")
        self.Canny = QAction(MainWindow)
        self.Canny.setObjectName(u"Canny")
        self.tailor = QAction(MainWindow)
        self.tailor.setObjectName(u"tailor")
        self.out2in = QAction(MainWindow)
        self.out2in.setObjectName(u"out2in")
        self.colorSeperate = QAction(MainWindow)
        self.colorSeperate.setObjectName(u"colorSeperate")
        self.singleLine = QAction(MainWindow)
        self.singleLine.setObjectName(u"singleLine")
        self.allLine = QAction(MainWindow)
        self.allLine.setObjectName(u"allLine")
        self.colorFFT = QAction(MainWindow)
        self.colorFFT.setObjectName(u"colorFFT")
        self.colorHigh = QAction(MainWindow)
        self.colorHigh.setObjectName(u"colorHigh")
        self.colorLow = QAction(MainWindow)
        self.colorLow.setObjectName(u"colorLow")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalSpacer_2 = QSpacerItem(17, 3, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_2)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        font = QFont()
        font.setFamily(u"\u9ed1\u4f53")
        font.setPointSize(16)
        self.label_2.setFont(font)

        self.horizontalLayout_2.addWidget(self.label_2)

        self.horizontalSpacer_4 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_4)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.horizontalLayout_2.addWidget(self.label)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_3)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.verticalSpacer = QSpacerItem(20, 5, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_5)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QSize(600, 630))
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        font1.setPointSize(12)
        self.tabWidget.setFont(font1)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setFont(font1)
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 711, 621))
        self.label_4.setPixmap(QPixmap(u"test.png"))
        self.label_4.setScaledContents(True)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(240, 270, 141, 71))
        font2 = QFont()
        font2.setFamily(u"\u9ed1\u4f53")
        font2.setPointSize(14)
        self.label_3.setFont(font2)
        self.tabWidget.addTab(self.tab, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.toIn = QPushButton(self.centralwidget)
        self.toIn.setObjectName(u"toIn")
        self.toIn.setMinimumSize(QSize(20, 0))
        font3 = QFont()
        font3.setFamily(u"\u9ed1\u4f53")
        font3.setPointSize(24)
        self.toIn.setFont(font3)

        self.horizontalLayout.addWidget(self.toIn)

        self.tabWidgetR = QTabWidget(self.centralwidget)
        self.tabWidgetR.setObjectName(u"tabWidgetR")
        sizePolicy.setHeightForWidth(self.tabWidgetR.sizePolicy().hasHeightForWidth())
        self.tabWidgetR.setSizePolicy(sizePolicy)
        self.tabWidgetR.setMinimumSize(QSize(600, 630))
        self.tabWidgetR.setFont(font1)
        self.tabWidgetR.setTabsClosable(False)
        self.tabWidgetR.setMovable(True)
        self.tabWidgetR.setTabBarAutoHide(True)
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setFont(font1)
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, -10, 671, 641))
        self.label_5.setPixmap(QPixmap(u"test1.png"))
        self.label_5.setScaledContents(True)
        self.tabWidgetR.addTab(self.tab_2, "")

        self.horizontalLayout.addWidget(self.tabWidgetR)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_7)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.verticalSpacer_3 = QSpacerItem(17, 3, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1344, 22))
        font4 = QFont()
        font4.setFamily(u"\u9ed1\u4f53")
        font4.setPointSize(12)
        self.menubar.setFont(font4)
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menuFFT = QMenu(self.menubar)
        self.menuFFT.setObjectName(u"menuFFT")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_5 = QMenu(self.menubar)
        self.menu_5.setObjectName(u"menu_5")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuFFT.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menu.addAction(self.open)
        self.menu.addAction(self.save)
        self.menu.addAction(self.saveR)
        self.menu.addAction(self.close)
        self.menu.addAction(self.closeR)
        self.menu_2.addAction(self.add)
        self.menu_2.addAction(self.reverse)
        self.menu_2.addAction(self.move)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.rotate)
        self.menu_2.addAction(self.enlarge)
        self.menu_2.addAction(self.shrink)
        self.menu_2.addAction(self.scale)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.histogram)
        self.menuFFT.addAction(self.FFT)
        self.menuFFT.addSeparator()
        self.menuFFT.addAction(self.high)
        self.menuFFT.addAction(self.low)
        self.menuFFT.addSeparator()
        self.menuFFT.addAction(self.colorHigh)
        self.menuFFT.addAction(self.colorLow)
        self.menuFFT.addSeparator()
        self.menuFFT.addAction(self.reconstruct)
        self.menu_3.addAction(self.Roberts)
        self.menu_3.addAction(self.Sobel)
        self.menu_3.addAction(self.Prewitt)
        self.menu_3.addAction(self.Scharr)
        self.menu_3.addAction(self.Laplacian)
        self.menu_3.addAction(self.Log)
        self.menu_3.addAction(self.Canny)
        self.menu_4.addAction(self.grey)
        self.menu_4.addAction(self.resize)
        self.menu_4.addAction(self.resizeAll)
        self.menu_5.addAction(self.tailor)
        self.menu_5.addAction(self.colorSeperate)
        self.menu_5.addAction(self.singleLine)
        self.menu_5.addAction(self.allLine)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.open.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
#if QT_CONFIG(shortcut)
        self.open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.save.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u5f53\u524d\u8f93\u5165", None))
#if QT_CONFIG(shortcut)
        self.save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.saveR.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u5f53\u524d\u8f93\u5165", None))
#if QT_CONFIG(shortcut)
        self.saveR.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.close.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u5f53\u524d\u8f93\u5165", None))
#if QT_CONFIG(shortcut)
        self.close.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.add.setText(QCoreApplication.translate("MainWindow", u"\u52a0\uff08\u6240\u6709\u6253\u5f00\u7684\u56fe\u50cf\uff09", None))
        self.reverse.setText(QCoreApplication.translate("MainWindow", u"\u6c42\u53cd", None))
        self.rotate.setText(QCoreApplication.translate("MainWindow", u"\u9006\u65f6\u9488\u65cb\u8f6c", None))
        self.histogram.setText(QCoreApplication.translate("MainWindow", u"\u76f4\u65b9\u56fe\u5747\u8861\u5316", None))
#if QT_CONFIG(shortcut)
        self.histogram.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+G", None))
#endif // QT_CONFIG(shortcut)
        self.FFT.setText(QCoreApplication.translate("MainWindow", u"\u5085\u91cc\u53f6\u53d8\u6362(\u8f93\u51faDFT/\u589e\u5f3a/\u53cd\u53d8\u6362\u56fe)", None))
#if QT_CONFIG(shortcut)
        self.FFT.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.a1D_FFT_center.setText(QCoreApplication.translate("MainWindow", u"1D-FFT\uff08\u4f4e\u9891\u4e2d\u5fc3\uff09", None))
        self.high.setText(QCoreApplication.translate("MainWindow", u"\u9ad8\u901a\u6ee4\u6ce2", None))
#if QT_CONFIG(shortcut)
        self.high.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.enlarge.setText(QCoreApplication.translate("MainWindow", u"\u653e\u59272\u500d", None))
#if QT_CONFIG(shortcut)
        self.enlarge.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+=", None))
#endif // QT_CONFIG(shortcut)
        self.shrink.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u5c0f2\u500d", None))
#if QT_CONFIG(shortcut)
        self.shrink.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+-", None))
#endif // QT_CONFIG(shortcut)
        self.scale.setText(QCoreApplication.translate("MainWindow", u"\u7b49\u6bd4\u7f29\u653e\u5230...", None))
        self.fouriour.setText(QCoreApplication.translate("MainWindow", u"\u5085\u91cc\u53f6\u63cf\u8ff0\u5b50", None))
        self.reconstruct.setText(QCoreApplication.translate("MainWindow", u"\u5085\u91cc\u53f6\u63cf\u8ff0\u5b50M\u9879\u6570\u91cd\u6784\uff08\u8f93\u51fa\u63cf\u8ff0\u5b50/\u91cd\u6784\u8f6e\u5ed3\uff09", None))
#if QT_CONFIG(shortcut)
        self.reconstruct.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+M", None))
#endif // QT_CONFIG(shortcut)
        self.Roberts.setText(QCoreApplication.translate("MainWindow", u"Roberts", None))
        self.Sobel.setText(QCoreApplication.translate("MainWindow", u"Sobel", None))
        self.Prewitt.setText(QCoreApplication.translate("MainWindow", u"Prewitt", None))
        self.Laplacian.setText(QCoreApplication.translate("MainWindow", u"Laplacian", None))
        self.resize.setText(QCoreApplication.translate("MainWindow", u"\u7b49\u6bd4\u7f29\u653e\u5230\u9002\u5e94\u7a97\u53e3", None))
#if QT_CONFIG(shortcut)
        self.resize.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.resizeAll.setText(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u7b49\u6bd4\u7f29\u653e\u5230\u9002\u5e94", None))
#if QT_CONFIG(shortcut)
        self.resizeAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.blend.setText(QCoreApplication.translate("MainWindow", u"\u6df7\u5408\uff08\u6240\u6709\u6253\u5f00\u7684\u56fe\u50cf\uff09", None))
        self.move.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u79fb", None))
        self.closeR.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u5f53\u524d\u8f93\u51fa", None))
#if QT_CONFIG(shortcut)
        self.closeR.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+W", None))
#endif // QT_CONFIG(shortcut)
        self.r1D_FFT.setText(QCoreApplication.translate("MainWindow", u"\u9006\u5085\u91cc\u53f6\u53d8\u6362", None))
#if QT_CONFIG(shortcut)
        self.r1D_FFT.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.r1D_FFT_center.setText(QCoreApplication.translate("MainWindow", u"\u90061D-FFT\uff08\u4f4e\u9891\u4e2d\u5fc3\uff09", None))
        self.gray.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u4e3a\u7070\u5ea6\u56fe", None))
        self.grey.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u4e3a\u7070\u5ea6\u56fe", None))
#if QT_CONFIG(shortcut)
        self.grey.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.low.setText(QCoreApplication.translate("MainWindow", u"\u4f4e\u901a\u6ee4\u6ce2", None))
#if QT_CONFIG(shortcut)
        self.low.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.Scharr.setText(QCoreApplication.translate("MainWindow", u"Scharr", None))
        self.Log.setText(QCoreApplication.translate("MainWindow", u"Log", None))
        self.Canny.setText(QCoreApplication.translate("MainWindow", u"Canny", None))
        self.tailor.setText(QCoreApplication.translate("MainWindow", u"\u88c1\u526a\u5750\u6807\u8f74", None))
#if QT_CONFIG(shortcut)
        self.tailor.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.out2in.setText(QCoreApplication.translate("MainWindow", u"\u5c06\u5f53\u524d\u8f93\u51fa\u79fb\u5230\u8f93\u5165", None))
#if QT_CONFIG(shortcut)
        self.out2in.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.colorSeperate.setText(QCoreApplication.translate("MainWindow", u"\u989c\u8272\u901a\u9053\u5206\u79bb", None))
#if QT_CONFIG(shortcut)
        self.colorSeperate.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.singleLine.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u53d6\u5355\u4e00\u66f2\u7ebf\u6570\u636e\u70b9", None))
#if QT_CONFIG(shortcut)
        self.singleLine.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.allLine.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u53d6\u66f2\u7ebf\u6570\u636e\u70b9\u5168\u6d41\u7a0b", None))
        self.colorFFT.setText(QCoreApplication.translate("MainWindow", u"\u5f69\u8272\u5085\u91cc\u53f6\u53d8\u6362", None))
#if QT_CONFIG(shortcut)
        self.colorFFT.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.colorHigh.setText(QCoreApplication.translate("MainWindow", u"\u5f69\u8272\u9ad8\u901a\u6ee4\u6ce2", None))
#if QT_CONFIG(shortcut)
        self.colorHigh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+H", None))
#endif // QT_CONFIG(shortcut)
        self.colorLow.setText(QCoreApplication.translate("MainWindow", u"\u5f69\u8272\u4f4e\u901a\u6ee4\u6ce2", None))
#if QT_CONFIG(shortcut)
        self.colorLow.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+L", None))
#endif // QT_CONFIG(shortcut)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u8f93\u5165", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8f93\u51fa", None))
        self.label_4.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u8bf7\u6253\u5f00\u4e00\u5f20\u56fe\u7247", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Default", None))
        self.toIn.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.label_5.setText("")
        self.tabWidgetR.setTabText(self.tabWidgetR.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Default", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u64cd\u4f5c", None))
        self.menuFFT.setTitle(QCoreApplication.translate("MainWindow", u"FFT", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u8fb9\u7f18\u68c0\u6d4b", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165", None))
        self.menu_5.setTitle(QCoreApplication.translate("MainWindow", u"\u63d0\u53d6", None))
    # retranslateUi

